#!/bin/sh

cat > $prefix.proj.in << EOF
 &projwfc
  prefix  = '$prefix'
  outdir = '$TMP_DIR/'
  ngauss = 0 
  degauss = 0.001
  Emin = $emin
  Emax = $emax
  DeltaE = 0.01
  lsym = .TRUE.
  filpdos = '$prefix.pdos'
  filproj = '$prefix.proj'
 /
EOF